POST http://localhost:3003/classes HTTP/1.1
content-type: application/json

{
    "name": "Pasche"

}
###
POST http://localhost:3003/teachers HTTP/1.1
content-type: application/json

{   
    "name": "Guilherme",
    "email": "guilherme@gmail.com",
    "birth": "13/07/1982",
    "class_id":"_268arfl9k2k",
    "expertise":"Typescript"
   
}